services:
  database:
    container_name: tsbin_db
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: tsbin
      POSTGRES_USER: tsbin
      POSTGRES_PASSWORD: tsbin
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
